# tyro YAML.
!dataclass:NeRFTrainingArgs
ckpt: null
common: !dataclass:CommonArgs
  logging: INFO
  seed: 1000000007
  summary: false
exp_dir: !!python/object/apply:pathlib.PosixPath []
frames_train: !!python/tuple
- !!python/object/apply:pathlib.PosixPath
  - PATH
- !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - cad_83
  - E
  - chenyingxi
  - jaxngp
  - data
  - nerf_synthetic
  - lego
  - transforms_train.json
frames_val: !!python/tuple []
raymarch: !dataclass:RayMarchingOptions
  density_grid_res: 128
  diagonal_n_steps: 1024
  perturb: true
raymarch_eval: !dataclass:RayMarchingOptions
  density_grid_res: 128
  diagonal_n_steps: 1024
  perturb: false
render: !dataclass:RenderingOptions
  bg: !!python/tuple
  - 1.0
  - 1.0
  - 1.0
  random_bg: true
render_eval: !dataclass:RenderingOptions
  bg: !!python/tuple
  - 0.0
  - 0.0
  - 0.0
  random_bg: false
scene: !dataclass:SceneOptions
  image_scale: 1.0
  world_scale: 1.0
train: !dataclass:TrainingArgs
  bs: 1048576
  data_loop: 1
  keep: 1
  keep_every: null
  lr: 0.01
  momentum: null
  n_batches: 1024
  n_epochs: 50
  validate_every: 10
