[colmap-locked]
src.github = "colmap/colmap"
fetch.github = "colmap/colmap"
git.fetchSubmodules = true

[dearpygui]
src.github = "hoffstadt/DearPyGui"
fetch.github = "hoffstadt/DearPyGui"
git.fetchSubmodules = true

[pycolmap]
src.github = "colmap/pycolmap"
fetch.github = "colmap/pycolmap"
git.fetchSubmodules = true

[pyimgui]
src.pypi = "imgui"
fetch.pypi = "imgui"

[tiny-cuda-nn]
src.github = "NVlabs/tiny-cuda-nn"
fetch.github = "NVlabs/tiny-cuda-nn"
git.fetchSubmodules = true

[tyro]
src.pypi = "tyro"
fetch.pypi = "tyro"
